### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by harukasan** [harukasan/ringo#7]
## Scanner
- [x] new line (8.3)
- [x] semicolon terminator (8.3)
- [x] whitespace (8.4)
- [x] escape new line (8.4)
- [x] comment (8.5)
- [x] multi line comment (8.5)
- [x] __END__ (8.6)
- [x] keywords (8.7.2)
- [x] identifiers (8.7.3)
- [x] delimiters (8.7.4)
- [x] operators (8.7.5)
- [x] number literals (8.7.6.2)
- [x] single quoted string (8.7.6.3.2)
- [x] double quoted string (8.7.6.3.3)
- [x] here document (8.7.6.3.6)
- [x] persent string (8.7.6.3.4, 8.7.6.3.5)
- [ ] external command (8.7.6.3.7)
- [ ] array literal (8.7.6.4)
- [ ] regexp (8.7.6.5)
- [ ] symbol (8.7.6.6)
## Parser
- [ ] AST
- [ ] IR
## ...
- [ ] TBD
